import { exec } from 'child_process';
import { promisify } from 'util';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import type {
  FixResult,
  ApprovalPolicyConfig,
  ModifiedFile,
} from './types/index.js';

const execAsync = promisify(exec);
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

let cachedPolicy: ApprovalPolicyConfig | null = null;

function loadApprovalPolicy(): ApprovalPolicyConfig {
  if (cachedPolicy) return cachedPolicy;
  const configPath = resolve(__dirname, '..', 'configs', 'approval-policy.json');
  const content = readFileSync(configPath, 'utf-8');
  cachedPolicy = JSON.parse(content) as ApprovalPolicyConfig;
  return cachedPolicy;
}

/**
 * 이슈 카테고리에서 커밋 scope를 매핑합니다.
 * COMMIT_CONVENTION 표준 준수.
 */
function categoryToScope(category: string): string {
  const map: Record<string, string> = {
    security: 'security',
    performance: 'perf',
    architecture: 'core',
    'code-quality': 'core',
    operations: 'ops',
    frontend: 'ui',
    testing: 'test',
  };
  return map[category] ?? 'core';
}

/**
 * PR 제목을 생성합니다.
 * COMMIT_CONVENTION 표준: fix(scope): subject (50자 이내)
 */
function buildPrTitle(fixResult: FixResult): string {
  const scope = categoryToScope(fixResult.category);
  // 브랜치명에서 설명 추출 (bugfix/39-slug → slug)
  const slug = fixResult.branchName
    ?.replace(/^(?:bugfix|fix|feature|hotfix)\/\d+-/, '')
    .replace(/-/g, ' ') ?? 'auto fix';
  return `fix(${scope}): ${slug}`.substring(0, 70);
}

/**
 * 수정된 파일 목록을 마크다운으로 포맷합니다.
 */
function formatModifiedFiles(files: ModifiedFile[]): string {
  if (files.length === 0) return '_No files modified_';

  return files
    .map((f) => `- \`${f.path}\` (${f.changeType}, +${f.linesAdded}/-${f.linesDeleted})`)
    .join('\n');
}

/**
 * 검증 결과를 마크다운으로 포맷합니다.
 */
function formatVerifications(fixResult: FixResult): string {
  if (fixResult.verifications.length === 0) return '_No verifications ran_';

  return fixResult.verifications
    .map((v) => {
      const icon = v.passed ? 'PASS' : 'FAIL';
      const duration = `${(v.durationMs / 1000).toFixed(1)}s`;
      return `- [${icon}] ${v.type}: \`${v.command}\` (${duration})`;
    })
    .join('\n');
}

/**
 * PR 본문을 생성합니다.
 */
function buildPrBody(fixResult: FixResult): string {
  const lines: string[] = [];

  lines.push('## Summary');
  lines.push('');
  lines.push(`- Issue #${fixResult.issueNumber} 자동 수정 (${fixResult.priority}, ${fixResult.category})`);
  lines.push(`- Strategy: ${fixResult.strategy}`);
  lines.push(`- Retry count: ${fixResult.retryCount}`);
  lines.push('');

  lines.push('## Modified Files');
  lines.push('');
  lines.push(formatModifiedFiles(fixResult.modifiedFiles));
  lines.push('');

  lines.push('## Verification Results');
  lines.push('');
  lines.push(formatVerifications(fixResult));
  lines.push('');

  lines.push('## Test Plan');
  lines.push('');
  lines.push('- [ ] 코드 리뷰 완료');
  lines.push('- [ ] 빌드 성공 확인');
  lines.push('- [ ] 기존 테스트 통과 확인');
  lines.push('- [ ] 기능 정상 동작 확인');
  lines.push('');

  lines.push(`fixes #${fixResult.issueNumber}`);
  lines.push('');
  lines.push('---');
  lines.push('Auto-generated by [Auto-Tobe-Agent](https://github.com/bluevlad/Auto-Tobe-Agent)');

  return lines.join('\n');
}

/**
 * 브랜치를 원격에 push합니다.
 */
async function pushBranch(branchName: string, cwd: string): Promise<void> {
  await execAsync(`git push -u origin ${branchName}`, {
    cwd,
    timeout: 60_000,
  });
}

/**
 * gh CLI로 PR을 생성합니다.
 */
async function createGhPr(
  repo: string,
  title: string,
  body: string,
  baseBranch: string,
  reviewers: string[],
  labels: string[],
  cwd: string,
): Promise<{ url: string; number: number }> {
  // body를 환경변수로 전달하여 shell 이스케이핑 문제 회피
  const escapedTitle = title.replace(/"/g, '\\"');
  const escapedBody = body.replace(/"/g, '\\"').replace(/\n/g, '\\n');

  let cmd = `gh pr create --repo ${repo} --title "${escapedTitle}" --body "${escapedBody}" --base ${baseBranch}`;

  if (reviewers.length > 0) {
    cmd += ` --reviewer ${reviewers.join(',')}`;
  }

  if (labels.length > 0) {
    cmd += ` --label ${labels.join(',')}`;
  }

  const { stdout } = await execAsync(cmd, {
    cwd,
    timeout: 30_000,
  });

  const prUrl = stdout.trim();

  // URL에서 PR 번호 추출
  const prNumberMatch = prUrl.match(/\/pull\/(\d+)/);
  const prNumber = prNumberMatch ? parseInt(prNumberMatch[1], 10) : 0;

  return { url: prUrl, number: prNumber };
}

/**
 * 수정 결과를 기반으로 PR을 생성합니다.
 *
 * 흐름: 정책 확인 → 브랜치 push → PR 생성 → 결과 업데이트
 */
export async function createPullRequest(
  fixResult: FixResult,
): Promise<FixResult> {
  const updated = { ...fixResult };
  const policyConfig = loadApprovalPolicy();
  const policy = policyConfig.policies[fixResult.priority];

  console.log(`\n[pr] #${fixResult.issueNumber} PR 생성 시작`);

  // 1. 정책 확인
  if (!policy.auto_pr) {
    console.log('  SKIP: 정책상 자동 PR 비활성화');
    return updated;
  }

  if (!fixResult.branchName) {
    console.log('  FAIL: 브랜치 이름 없음');
    updated.status = 'failed';
    updated.error = 'No branch name in fix result';
    return updated;
  }

  // fix가 성공적이었는지 확인 (build_verified 또는 test_verified)
  const validStatuses = ['build_verified', 'test_verified', 'fix_applied'];
  if (!validStatuses.includes(fixResult.status)) {
    console.log(`  SKIP: 유효하지 않은 상태 (${fixResult.status})`);
    return updated;
  }

  try {
    // 2. 프로젝트 로컬 경로에서 작업
    const projectsConfigPath = resolve(__dirname, '..', 'configs', 'projects.json');
    const projectsContent = readFileSync(projectsConfigPath, 'utf-8');
    const projectsConfig = JSON.parse(projectsContent);
    const projectConfig = projectsConfig.projects[fixResult.project];
    const cwd = projectConfig?.local_path;

    if (!cwd) {
      throw new Error(`Project "${fixResult.project}" local_path not found`);
    }

    // 3. 브랜치 push
    console.log(`  Pushing ${fixResult.branchName}...`);
    await pushBranch(fixResult.branchName, cwd);

    // 4. PR 생성
    const title = buildPrTitle(fixResult);
    const body = buildPrBody(fixResult);
    const reviewers = policy.required_reviewers.length > 0
      ? policy.required_reviewers
      : policyConfig.default_reviewers;
    const labels = [`${fixResult.priority}`, fixResult.category, 'auto-fix'];

    console.log(`  Creating PR: ${title}`);
    const pr = await createGhPr(
      fixResult.repo,
      title,
      body,
      projectConfig.main_branch,
      reviewers,
      labels,
      cwd,
    );

    updated.prUrl = pr.url;
    updated.prNumber = pr.number;
    updated.status = 'pr_created';

    console.log(`  PR created: ${pr.url}`);

    return updated;
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    console.log(`  PR creation failed: ${errMsg}`);
    updated.error = `PR creation failed: ${errMsg}`;
    return updated;
  }
}

// export for testing
export { buildPrTitle, buildPrBody };
